package com.bhhan.dynamo.domain;

import com.amazonaws.services.dynamodbv2.datamodeling.*;
import com.bhhan.dynamo.config.DynamoDbConfig;
import lombok.Builder;
import lombok.Getter;
import lombok.NoArgsConstructor;
import lombok.Setter;

import java.time.LocalDateTime;

/**
 * Created by hbh5274@gmail.com on 2020-08-06
 * Github : http://github.com/bhhan5274
 */

@DynamoDBTable(tableName = "Comment")
@NoArgsConstructor
@Getter
@Setter
public class Comment {
    @DynamoDBHashKey(attributeName = "id")
    @DynamoDBAutoGeneratedKey
    private String id;

    @DynamoDBAttribute
    @DynamoDBIndexHashKey(globalSecondaryIndexName = "byMentionId")
    private Integer mentionId;

    @DynamoDBAttribute
    private String name;

    @DynamoDBAttribute
    private String content;

    @DynamoDBAttribute
    @DynamoDBTyped(DynamoDBMapperFieldModel.DynamoDBAttributeType.BOOL)
    private boolean deleted;

    @DynamoDBAttribute
    @DynamoDBIndexRangeKey(globalSecondaryIndexName = "byMentionId")
    @DynamoDBTypeConverted(converter = DynamoDbConfig.LocalDateTimeConverter.class)
    private LocalDateTime createdAt;

    @DynamoDBAttribute
    @DynamoDBTypeConverted(converter = DynamoDbConfig.LocalDateTimeConverter.class)
    private LocalDateTime deletedAt;

    @Builder
    public Comment(String id, Integer mentionId, String name, String content, boolean deleted,
                   LocalDateTime createdAt, LocalDateTime deletedAt){
        this.id = id;
        this.mentionId = mentionId;
        this.name = name;
        this.content = content;
        this.deleted = deleted;
        this.createdAt = createdAt;
        this.deletedAt = deletedAt;
    }

    public void update(String modifiedContent) {
        this.content = modifiedContent;
    }
}
